language: node_js
node_js: stable
# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-cli -g  
  - npm install -- save-dev hexo-util
  - npm install hexo-deployer-git --save
  - npm install hexo-generator-feed --save
#before_script:
 # - npm install -g gulp
script:
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "wanqinlong"
  - git config user.email "304920689@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle
branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/wanqinlong/wanqinlong.github.io.git
