# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

# 添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  home:
    text: 博客主页
    url: /
  archives: 
    text: 最新文章
    url: /archives
  th-list:
    text: 文章分类
    url: /categories
  tags:
    text: 文章标签
    url: /tags
  id-card: # address-book user-circle
    text: 关于博主
    url: /about
  #address-book: # address-book user-circle 【试过了，可以添加“最近”单独页，可用来写一些信息】
    #text: 最近
    #url: /zuijin
  weibo:
    text: 微博
    url: http://weibo.com/u/5643460167
    target: _blank
  hand-peace-o:
    text: 小岛
    url: http://weibo.com/HymanW
    target: _blank
  book: # book   address-book
    text: 简书
    url: http://www.jianshu.com/u/d49d8f622a49
    target: _blank
  android:
    text: 笔记
    url: http://www.cnblogs.com/wanqinlong/
    target: _blank
  #github:
    #url: https://github.com/wanqinlong
    #target: _blank
  #link:
    #text: 测试
    #url: /custom

# 你的头像url
avatar: /img/avatar.jpg
# avatar link
avatar_link: /
# 头像背景图
brand: /img/brand.jpg
# favicon
favicon: /favicon.ico

# email
email: wanqinlongjob@gmail.com

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#3F51B5'

# 页面标题
tags_title: Tags
archives_title: Archives
categories_title: Categories

# 文章截断
    # 1、文章摘要渲染方式: 为 true 时将渲染为 html，否则为文本
    # 可以在 Markdown 文件中加 <!--more-->以分割摘要与文章正文。未设置时，按 excerpt_length 设置截取。
    #excerpt_render: true   设置为 true 为图文并茂展开，设置为 false 为小卡片
    # 2、开启后，使你的站点支持公式渲染，by mathjax。 请按需开启，因为此项需要加载额外的 js 文件。
excerpt_render: true
excerpt_length: 200
excerpt_link: 阅读全文...
mathjax: false
archive_yearly: true

# 是否显示文章最后更新时间 【】
show_last_updated: false

# 是否开启分享，文章分享开关，by jiathis-api。
share: true



# 是否开启打赏，关闭 reward: false
# 此外在 crad theme 中，可以通过在 markdown 头部添加 reward: false 来控制某些不想开启打赏的页面。
reward:
  title: 谢谢支持
  wechat: /img/wechat.jpg     #微信，关闭设为 false
  alipay: /img/alipay.jpg     #支付宝，关闭设为 false

# 站内搜索：是否开启搜索
search: true

# 布局：是否大屏幕下文章页隐藏导航。开启后，文章页在大屏下会隐藏左侧菜单，专注阅读。
hideMenu: true

# 是否开启toc，开启文章内容导航。
# toc: false
#   list_number: true  # 是否显示数字排序 # 决定导航使用的标签， true 为 ol， false 为 ul。
toc:
  list_number: true

# 文章页留言内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
#(我去掉的)postMessage: 这里可以写作者留言，标签和 hexo 中所有变量及辅助函数等均可调用，示例：<a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- url.replace(/index\.html$/, '') %></a>
postMessage: 有什么问题，可以邮件我 wanqinlongjob@gmail.com ，或者在微博<a href=" http://weibo.com/u/5643460167"> @万秦龙 </a>上私信我，或者也可以加我微信。<br><div align="center"><img src="http://wx3.sinaimg.cn/large/0069VnN5gy1ffjvs9qj3bj303m04574x.jpg"  /></div> <br><div class="text" style=" text-align:center;">WeChat</div>
# 站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz: false

# 百度统计，如要开启，改为你的 key
baidu_tongji: false

# 腾讯分析，如要开启，输入站点id
tajs: false

# google
google_analytics: false
google_site_verification: false

# less ，设置 less 编译时的入口文件路径，hexo-renderer-less。
# compress: true    # 是否压缩css
less:
  compress: true
  paths:
    - source/css/style.less

# 以下评论插件开启一个即可
# 是否开启多说评论，填写你在多说创建的站点二级域名
duoshuo: false
# 是否开启多说评论计数（该服务不稳定）
duoshuo_count: false
# 使用 disqus 时关闭多说评论
disqus_shortname: false
# 是否开启友言评论, 填写友言用户id
uyan_uid: false
# 是否开启网易云跟帖， 填写app sdk中的app key
wangyi_ygt: 77ab315ba35e4a9fba801ece5562c92d
# 是否使用 gitment，https://github.com/imsun/gitment
gitment: false
# gitment:
#   owner:
#   repo:
#   client_id:
#   client_secret:

# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical: http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical: http://wanqinlong.com

# 版权起始年份
since_year: 2017

# 用户页面中作者相关的描述性文字，如不需要设为 false
#about: true
#about: false

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
#visit_counter:
  #site_uv: 站点总访客数：
  #site_pv: 站点总访问量：

# 动态定义title
title_change:
  normal: 万秦龙
  leave: Hyman Wan

# 设置为 true 发布后将使用 unpkg cdn
cdn: true

# 设置为 true 将使用 lightbox render 图片
lightbox: true
